vm_control: send error contexts for VmMemoryResponse::Err
Example panic message:

2025-04-17T21:31:21.680849800-07:00
Panic at location:
devices\src\virtio\vhost_user_frontend\mod.rs:383
message: panicked at devices\src\virtio\vhost_user_frontend\mod.rs:383:18:
called `Result::unwrap()` on an `Err` value: vu-gpu: vhost_user_frontend worker failed

Caused by:
    0: failed to handle vhost-user request
    1: handler failed to handle request: add Vulkan source mapping
    2: add Vulkan source mapping
    3: register_memory failed
    4: Request failed: gralloc mapping
    5: gralloc mapping
    6: gralloc failed to import and map, handle type: 3, memory index 3, size: 8388608
    7: ash failure Extension specified does not exist

Note that cause 5-7 are the contexts propagated from VmMemoryRequest::execute through VmMemoryResponse.

Test: presubmit
Bug: b/394669524
Bug: b/396183057
Change-Id: I8858e7ebf5af750b38ddbbdd9712aeba1fc2cb22
Reviewed-on: https://chromium-review.googlesource.com/c/crosvm/crosvm/+/6471316
Reviewed-by: Daniel Verkamp <dverkamp@chromium.org>
Commit-Queue: Kaiyi Li <kaiyili@google.com>