vmm_vhost: print details for ReqHandlerError
An example of the panic message is:

2025-04-17T07:50:04.949077300-07:00
Panic at location:
devices\src\virtio\vhost_user_frontend\mod.rs:383
message: panicked at devices\src\virtio\vhost_user_frontend\mod.rs:383:18:
called `Result::unwrap()` on an `Err` value: vu-gpu: vhost_user_frontend worker failed

Caused by:
2025-04-17T10:47:44.596148900-07:00
Panic at location:
devices\src\virtio\vhost_user_frontend\mod.rs:383
message: panicked at devices\src\virtio\vhost_user_frontend\mod.rs:383:18:
called `Result::unwrap()` on an `Err` value: vu-gpu: vhost_user_frontend worker failed

Caused by:
    0: failed to handle vhost-user request
    1: handler failed to handle request: add Vulkan source mapping
    2: add Vulkan source mapping
    3: register_memory failed
    4: Request failed: The device does not recognize the command. (os error 22)
    5: The device does not recognize the command. (os error 22)

Bug: b/394669524
Change-Id: If25648f35681989e7edc31841eb22a6ee13d75bf
Reviewed-on: https://chromium-review.googlesource.com/c/crosvm/crosvm/+/6470072
Reviewed-by: Noah Gold <nkgold@google.com>
Commit-Queue: Kaiyi Li <kaiyili@google.com>