base: netlink: remove unused family_name_query variable
Remove the _bytes_read variable, since it is not needed. It was also
misnamed since we are writing, not reading, data.

Fixes a Rust 1.62 clippy lint:

  error: this let-binding has unit value

BUG=b:243677117
TEST=tools/clippy # with Rust 1.62

Change-Id: I53f7b675f8e95c94ab127e500127a9153166a906
Reviewed-on: https://chromium-review.googlesource.com/c/crosvm/crosvm/+/3854968
Commit-Queue: Daniel Verkamp <dverkamp@chromium.org>
Reviewed-by: Dennis Kempin <denniskempin@google.com>
Tested-by: Daniel Verkamp <dverkamp@chromium.org>