rutabaga_gfx: kumquat: nullptr check
Fixes the following error with newer Rust:

thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
   unsafe precondition(s) violated: slice::from_raw_parts requires
   the pointer to be aligned and non-null, and the total size of
   the slice not to exceed `isize::MAX`

BUG=b:409644321
TEST=vulkaninfo via kumquat

Change-Id: I08fbfbadd4cce2c9ae306adc68f6730ef6779f5f
Reviewed-on: https://chromium-review.googlesource.com/c/crosvm/crosvm/+/6442915
Commit-Queue: Gurchetan Singh <gurchetansingh@chromium.org>
Auto-Submit: Gurchetan Singh <gurchetansingh@chromium.org>
Reviewed-by: Frederick Mayle <fmayle@google.com>
Reviewed-by: Daniel Verkamp <dverkamp@chromium.org>