data_model: Add safety section for unsafe functions
When running presubmit for a module depends on sys_util, clippy shows
the following error message.

error: unsafe function's docs miss `# Safety` section
  --> .../src/platform/crosvm/data_model/src/flexible_array.rs:77:5
   |
77 |     unsafe fn get_slice(&self, len: usize) -> &[S];
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D clippy::missing-safety-doc` implied by `-D warnings`

BUG=none
TEST=Cq preflight

Change-Id: If296f145b68d6c2734a0fb58b37fd0452791aed7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/crosvm/+/2879285
Reviewed-by: Kuo-Hsin Yang <vovoy@chromium.org>
Reviewed-by: Gurchetan Singh <gurchetansingh@chromium.org>
Reviewed-by: Zach Reizner <zachr@chromium.org>
Auto-Submit: Kuo-Hsin Yang <vovoy@chromium.org>
Tested-by: kokoro <noreply+kokoro@google.com>
Commit-Queue: Kuo-Hsin Yang <vovoy@chromium.org>